### ISSUE TITLE
Fail to detect tie in some cases?

### ISSUE THREAD

**Issue by ghjgghj** [aliang/pokerhand-eval#9] opened 2020-12-30 05:47 UTC
seems to me it fails to detect a tie in some cases. see example:

hole_1 = [Card(14, 2), Card(13, **1**)]
hole_2 = [Card(14, 4), Card(13, 2)]
board = [Card(14, 3), Card(3, **1**), Card(4, **1**), Card(5, 2), Card(6, **1**)]
score_1 = HandEvaluator.evaluate_hand(hole_1, board)
score_2 = HandEvaluator.evaluate_hand(hole_2, board)
print(score_1)
print(score_2)

0.5575757575757576
0.5510101010101011

for it works fine in other cases:

hole_1 = [Card(14, 2), Card(13, **1**)]
hole_2 = [Card(14, 4), Card(13, 2)]
board = [Card(14, 3), Card(3, **1**), Card(4, 2), Card(5, 2), Card(6, **1**)]
score_1 = HandEvaluator.evaluate_hand(hole_1, board)
score_2 = HandEvaluator.evaluate_hand(hole_2, board)
print(score_1)
print(score_2)

0.5777777777777777
0.5777777777777777

It seems to score four cards of the suit higher.

**Comment by aliang** [comment] 2021-01-15 23:17
This might be a bug yeah. Need to think about this. If it's really a bug probably need to regenerate the lookup tables

**Comment by aliang** [comment] 2021-02-03 17:54
After looking at the code again, I think this is expected behavior for the reason I specified in my previous comment. Closing for now, please reopen if you have more questions.

**Closed by aliang** 2021-02-03 17:54 UTC
